# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8b4cca15d893f3e5c967442cb827b37d9c8d9248ca4df54fb738da6083f8cc54dd7fcc0e898189553ed200d0f161d1c47930a7c9d1252513eb831e73dca9df

test:
  secret_key_base: b2bce8fcc694b7d85c7761fa6a736fb485686d74248b1c1150db7824d0b9e341e5022c45f32ed51528fb7660d82386d688b0449ec54fcddebe1aa2c3572ca368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
